import { PropostaComItens, gerarPdfPropostaSimples } from "./SimpleProposalPdf";
export const MOCK_PROPOSTA: PropostaComItens = {
  id: "mock-id",
  numero: "P-0001",
  titulo: "Proposta de exemplo para produção de vídeos",
  introducao:
    "Obrigado pela oportunidade! Esta é uma proposta de exemplo para validarmos o layout de visualização.",
  moeda: "BRL",
  status: "enviada",
  valorTotal: 12000,
  empresaId: "empresa-mock",
  empresa: {
    id: "empresa-mock",
    nome: "Empresa Exemplo Ltda.",
    porte: "medio",
    status: 1,
    criadoEm: new Date().toISOString(),
    atualizadoEm: new Date().toISOString(),
  } as any,
  contatoId: "contato-mock",
  contato: {
    id: "contato-mock",
    nome: "Fulano de Tal",
    status: 1 as any,
    lead: "morno",
    tipoContato: "cliente",
    diasProximoContato: 0,
    proximoContato: new Date().toISOString(),
    numeroContatos: 0,
    perfilAtual: 1,
    tentativasPerfil1: 0,
    tentativasPerfil2: 0,
    tentativasPerfil3: 0,
    empresaId: "empresa-mock",
    usuarioCriadorId: "usuario-mock",
    criadoEm: new Date().toISOString(),
    atualizadoEm: new Date().toISOString(),
  } as any,
  usuarioCriadorId: "usuario-mock",
  usuarioCriador: {
    id: "usuario-mock",
    login: "usuario.mock",
    nome: "Equipe FilmeLab",
    email: "contato@filmelab.com.br",
    funcao: "Atendimento",
    notificacoes: { ativada: false, diasAntes: 0 },
    criadoEm: new Date().toISOString(),
    atualizadoEm: new Date().toISOString(),
  },
  itens: [
    {
      id: "item-1",
      propostaId: "mock-id",
      nome: "Produção de vídeos institucionais",
      descricao: "Produção, captação e edição de vídeos institucionais.",
      inclui: "Pré-produção, roteiro, captação e edição.",
      naoInclui: "Locação de espaço, cachê de atores e trilha paga.",
      quantidade: 1,
      precoUnitario: 8000,
      tipoDesconto: null,
      valorDesconto: null,
      precoTotal: 8000,
      ordem: 1,
    },
    {
      id: "item-2",
      propostaId: "mock-id",
      nome: "Conteúdos curtos para redes sociais",
      descricao: "Pacote de vídeos curtos otimizados para redes sociais.",
      inclui: "Edição em formatos verticais, inserção de legendas.",
      naoInclui: "Gestão de tráfego pago.",
      quantidade: 10,
      precoUnitario: 400,
      tipoDesconto: "percentual",
      valorDesconto: 10,
      precoTotal: 3600,
      ordem: 2,
    },
  ],
  criadoEm: new Date().toISOString(),
  atualizadoEm: new Date().toISOString(),
};
